version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - SERVICE_A_URL=http://service-a:3001
      - SERVICE_B_URL=http://service-b:3002
    depends_on:
      - service-a
      - service-b
    networks:
      - microservices-network
    restart: unless-stopped

  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - microservices-network
    restart: unless-stopped

  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge
